enum InfrastructureErrorCode {
    // Database
    DB_CONNECTION_FAILED = 'DB_CONNECTION_FAILED',
    DB_QUERY_FAILED = 'DB_QUERY_FAILED',
    DB_TRANSACTION_FAILED = 'DB_TRANSACTION_FAILED',
    DB_CONSTRAINT_VIOLATION = 'DB_CONSTRAINT_VIOLATION',

    // Redis
    REDIS_CONNECTION_FAILED = 'REDIS_CONNECTION_FAILED',
    REDIS_AUTH_FAILED = 'REDIS_AUTH_FAILED',
    REDIS_COMMAND_FAILED = 'REDIS_COMMAND_FAILED',

    // BullMQ
    QUEUE_CONNECTION_FAILED = 'QUEUE_CONNECTION_FAILED',
    QUEUE_JOB_ADD_FAILED = 'QUEUE_JOB_ADD_FAILED',
    QUEUE_JOB_PROCESS_FAILED = 'QUEUE_JOB_PROCESS_FAILED',

    // Typesense Search
    TYPESENSE_INIT_FAILED = 'TYPESENSE_INIT_FAILED',
    TYPESENSE_UNAVAILABLE = 'TYPESENSE_UNAVAILABLE',
    TYPESENSE_TIMEOUT = 'TYPESENSE_TIMEOUT',
    TYPESENSE_SEARCH_FAILED = 'TYPESENSE_SEARCH_FAILED',
    TYPESENSE_COLLECTION_CREATE_FAILED = 'TYPESENSE_COLLECTION_CREATE_FAILED',
    TYPESENSE_INDEX_UPDATE_FAILED = 'TYPESENSE_INDEX_UPDATE_FAILED',

    // Search index
    SEARCH_INDEX_REBUILD_FAILED = 'SEARCH_INDEX_REBUILD_FAILED',

    // Google Cloud
    GSA_MISSING_CREDENTIALS = 'GSA_MISSING_CREDENTIALS',
    GSA_TOKEN_ACQUISITION_FAILED = 'GSA_TOKEN_ACQUISITION_FAILED',
    GOOGLE_API_REQUEST_FAILED = 'GOOGLE_API_REQUEST_FAILED',

    // SMTP
    SMTP_NOT_CONFIGURED = 'SMTP_NOT_CONFIGURED',
    SMTP_CONNECT_FAILED = 'SMTP_CONNECT_FAILED',
    SMTP_AUTH_FAILED = 'SMTP_AUTH_FAILED',
    SMTP_SEND_FAILED = 'SMTP_SEND_FAILED',

    // Rate limiting
    RATE_LIMIT_REDIS_UNAVAILABLE = 'RATE_LIMIT_REDIS_UNAVAILABLE',

    // Cron jobs
    CRON_SCHEDULER_FAILED = 'CRON_SCHEDULER_FAILED',

    // File storage
    FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
    FILE_STORAGE_UNAVAILABLE = 'FILE_STORAGE_UNAVAILABLE',

    // External API calls
    EXTERNAL_API_TIMEOUT = 'EXTERNAL_API_TIMEOUT',
    EXTERNAL_API_5XX = 'EXTERNAL_API_5XX',

    // Rate limiting
    RATE_LIMIT_UNKNOWN_IP = 'RATE_LIMIT_UNKNOWN_IP'
}

enum ApplicationErrorCode {
    DEFAULT = 'DEFAULT',
    BAD_REQUEST = 'BAD_REQUEST',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    NOT_FOUND = 'NOT_FOUND',
    CONFLICT = 'CONFLICT',
    TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
    NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
    PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
    PRECONDITION_FAILED = 'PRECONDITION_FAILED',
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
    UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',

    // Validation
    VALIDATION_FAILED = 'VALIDATION_FAILED',
    MISSING_FIELD = 'MISSING_FIELD',
    INVALID_FORMAT = 'INVALID_FORMAT',
    UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE',

    // Authentication
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    TOKEN_INVALID = 'TOKEN_INVALID',
    EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
    EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED',
    GOOGLE_OAUTH_FAILED = 'GOOGLE_OAUTH_FAILED',
    SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
    ALREADY_LOGGED_IN = 'ALREADY_LOGGED_IN',

    // User domain
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    PASSWORD_TOO_WEAK = 'PASSWORD_TOO_WEAK',
    PASSWORD_RESET_TOKEN_INVALID = 'PASSWORD_RESET_TOKEN_INVALID',
    PASSWORD_RESET_TOKEN_EXPIRED = 'PASSWORD_RESET_TOKEN_EXPIRED',
    EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
    EMAIL_CHANGE_TOKEN_EXPIRED = 'EMAIL_CHANGE_TOKEN_EXPIRED',
    INVALID_PASSWORD = 'INVALID_PASSWORD',

    // Recipe domain
    RECIPE_NOT_FOUND = 'RECIPE_NOT_FOUND',
    RECIPE_ALREADY_EXISTS = 'RECIPE_ALREADY_EXISTS',
    RECIPE_ACCESS_DENIED = 'RECIPE_ACCESS_DENIED',
    INGREDIENT_LIMIT_EXCEEDED = 'INGREDIENT_LIMIT_EXCEEDED',
    RATING_DUPLICATE = 'RATING_DUPLICATE',

    // File uploads
    FILE_TYPE_UNSUPPORTED = 'FILE_TYPE_UNSUPPORTED',
    FILE_TOO_LARGE = 'FILE_TOO_LARGE',
    IMAGE_PROCESSING_FAILED = 'IMAGE_PROCESSING_FAILED',

    // Search
    SEARCH_QUERY_INVALID = 'SEARCH_QUERY_INVALID',
    SEARCH_BACKEND_UNAVAILABLE = 'SEARCH_BACKEND_UNAVAILABLE',
    SEARCH_TIMEOUT = 'SEARCH_TIMEOUT',

    // Queue
    JOB_NOT_FOUND = 'JOB_NOT_FOUND',
    JOB_FAILED = 'JOB_FAILED',
    JOB_STILL_PROCESSING = 'JOB_STILL_PROCESSING',

    // Business errors
    PRECONDITION_REQUIRED = 'PRECONDITION_REQUIRED',
    DEPENDENCY_FAILED = 'DEPENDENCY_FAILED'
}

export { InfrastructureErrorCode, ApplicationErrorCode };

export type ServerErrorCode = InfrastructureErrorCode | ApplicationErrorCode;
