export const CS_TAG_CATEGORIES = {
    cuisine: [
        'americká',
        'italská',
        'francouzská',
        'čínská',
        'mexická',
        'indická',
        'řecká',
        'japonská',
        'středomořská',
        'thajská',
        'španělská',
        'německá',
        'korejská',
        'blízký východ',
        'skandinávská',
        'vietnamská',
        'britská',
        'arabská',
        'česká',
        'evropská',
        'jihoamerická',
        'polská',
        'rakouská',
        'slovenská'
    ],
    difficulty: [
        'velmi snadné',
        'snadné',
        'těžké',
        'časově náročné',
        'rychlá příprava',
        'málo surovin',
        'vhodné pro začátečníky',
        'pokročilé'
    ],
    season: [
        'jaro',
        'léto',
        'podzim',
        'zima',
        'svátky',
        'Vánoce',
        'Velikonoce'
    ],
    definedBy: [
        'hovězí',
        'kuřecí',
        'vepřové',
        'krůtí',
        'jehněčí',
        'ryby',
        'mořské plody',
        'vejce',
        'mléko a smetana',
        'sýr',
        'luštěniny',
        'kořenová zelenina',
        'houby',
        'ovoce',
        'ořechy',
        'semínka',
        'těstoviny',
        'obiloviny',
        'rýže',
        'chléb',
        'tofu',
        'zelenina'
    ],
    type: [
        'předkrm',
        'polévka',
        'salát',
        'sendvič',
        'wrap',
        'hlavní chod',
        'příloha',
        'omáčka',
        'dresink',
        'svačina',
        'dezert',
        'dort',
        'koláč',
        'chléb',
        'pečivo',
        'palačinky',
        'grilování',
        'pečeně',
        'pečení',
        'smažení',
        'pizza',
        'burger',
        'z jednoho hrnce',
        'tlakový hrnec',
        'zdravé',
        'lehké jídlo',
        'levné jídlo',
        'piknik',
        'pohoštění',
        'snídaně',
        'večeře',
        'nápoj',
        'pálivé'
    ],
    diet: [
        'bez lepku',
        'bez laktózy',
        'vegetariánské',
        'veganské',
        'bez cukru',
        'paleo'
    ]
} as const satisfies Record<string, readonly string[]>;
