export const ENV_CONFIG = Object.freeze({
    ENV: process.env.NEXT_PUBLIC_ENV,
    API_URL: process.env.NEXT_PUBLIC_API_URL,
    GOOGLE_OAUTH_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_ID,
    ORIGIN: process.env.NEXT_PUBLIC_ORIGIN,
    COOKIE_DOMAIN: process.env.NEXT_PUBLIC_COOKIE_DOMAIN,
    GOOGLE_STORAGE_BUCKET_RECIPE_IMAGES:
        process.env.NEXT_PUBLIC_GOOGLE_STORAGE_BUCKET_RECIPE_IMAGES
});
