import { iconsSvg } from './svg';

export const icons = {
    bell: iconsSvg.BellIcon,
    book: iconsSvg.BookIcon,
    cancel: iconsSvg.CancelIcon,
    cart: iconsSvg.CartIcon,
    checkmark: iconsSvg.CheckmarkIcon,
    chevronDoubleUp: iconsSvg.ChevronDoubleUpIcon,
    chevronDoubleDown: iconsSvg.ChevronDoubleDownIcon,
    chevronDoubleLeft: iconsSvg.ChevronDoubleLeftIcon,
    chevronDoubleRight: iconsSvg.ChevronDoubleRightIcon,
    close: iconsSvg.CloseIcon,
    drag: iconsSvg.DragIcon,
    error: iconsSvg.ErrorIcon,
    exit: iconsSvg.ExitIcon,
    home: iconsSvg.HomeIcon,
    google: iconsSvg.GoogleIcon,
    info: iconsSvg.InfoIcon,
    moon: iconsSvg.MoonIcon,
    plus: iconsSvg.PlusIcon,
    servings: iconsSvg.ServingsIcon,
    search: iconsSvg.SearchIcon,
    shoppingList: iconsSvg.ShoppingListIcon,
    star: iconsSvg.StarIcon,
    starFull: iconsSvg.StarFullIcon,
    starHalf: iconsSvg.StarHalfIcon,
    sun: iconsSvg.SunIcon,
    time: iconsSvg.TimeIcon,
    threeDots: iconsSvg.ThreeDotsIcon,
    upload: iconsSvg.UploadIcon
};
