import { iconsSvg } from './svg';

export const icons = {
    bell: iconsSvg.BellIcon,
    book: iconsSvg.BookIcon,
    cancel: iconsSvg.CancelIcon,
    cart: iconsSvg.CartIcon,
    checkmark: iconsSvg.CheckmarkIcon,
    chevronDown: iconsSvg.ChevronDownIcon,
    chevronDoubleUp: iconsSvg.ChevronDoubleUpIcon,
    chevronDoubleDown: iconsSvg.ChevronDoubleDownIcon,
    chevronDoubleLeft: iconsSvg.ChevronDoubleLeftIcon,
    chevronDoubleRight: iconsSvg.ChevronDoubleRightIcon,
    close: iconsSvg.CloseIcon,
    delete: iconsSvg.DeleteIcon,
    drag: iconsSvg.DragIcon,
    edit: iconsSvg.EditIcon,
    email: iconsSvg.EmailIcon,
    error: iconsSvg.ErrorIcon,
    exit: iconsSvg.ExitIcon,
    facebook: iconsSvg.FacebookIcon,
    google: iconsSvg.GoogleIcon,
    home: iconsSvg.HomeIcon,
    info: iconsSvg.InfoIcon,
    link: iconsSvg.LinkIcon,
    moon: iconsSvg.MoonIcon,
    plus: iconsSvg.PlusIcon,
    search: iconsSvg.SearchIcon,
    servings: iconsSvg.ServingsIcon,
    share: iconsSvg.ShareIcon,
    shoppingList: iconsSvg.ShoppingListIcon,
    star: iconsSvg.StarIcon,
    starFull: iconsSvg.StarFullIcon,
    starHalf: iconsSvg.StarHalfIcon,
    sun: iconsSvg.SunIcon,
    time: iconsSvg.TimeIcon,
    threeDots: iconsSvg.ThreeDotsIcon,
    twitter: iconsSvg.TwitterIcon,
    upload: iconsSvg.UploadIcon,
    whatsapp: iconsSvg.WhatsappIcon
};
